// 

// 

package com.inspur.resources.view.tube;

import java.util.ArrayList;
import java.util.List;

import com.inspur.easyresources.R;
import com.inspur.resources.base.BaseActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.TableRow;

public class WellcodeShaixuanActivity extends BaseActivity
{
    private CheckBox CheckBox1;
    private CheckBox CheckBox10;
    private CheckBox CheckBox100;
    private CheckBox CheckBox101;
    private CheckBox CheckBox102;
    private CheckBox CheckBox103;
    private CheckBox CheckBox104;
    private CheckBox CheckBox105;
    private CheckBox CheckBox106;
    private CheckBox CheckBox107;
    private CheckBox CheckBox108;
    private CheckBox CheckBox109;
    private CheckBox CheckBox11;
    private CheckBox CheckBox110;
    private CheckBox CheckBox111;
    private CheckBox CheckBox112;
    private CheckBox CheckBox113;
    private CheckBox CheckBox114;
    private CheckBox CheckBox115;
    private CheckBox CheckBox116;
    private CheckBox CheckBox117;
    private CheckBox CheckBox118;
    private CheckBox CheckBox119;
    private CheckBox CheckBox12;
    private CheckBox CheckBox120;
    private CheckBox CheckBox121;
    private CheckBox CheckBox122;
    private CheckBox CheckBox123;
    private CheckBox CheckBox124;
    private CheckBox CheckBox125;
    private CheckBox CheckBox126;
    private CheckBox CheckBox127;
    private CheckBox CheckBox128;
    private CheckBox CheckBox129;
    private CheckBox CheckBox13;
    private CheckBox CheckBox130;
    private CheckBox CheckBox131;
    private CheckBox CheckBox132;
    private CheckBox CheckBox133;
    private CheckBox CheckBox134;
    private CheckBox CheckBox135;
    private CheckBox CheckBox136;
    private CheckBox CheckBox137;
    private CheckBox CheckBox138;
    private CheckBox CheckBox139;
    private CheckBox CheckBox14;
    private CheckBox CheckBox140;
    private CheckBox CheckBox141;
    private CheckBox CheckBox142;
    private CheckBox CheckBox143;
    private CheckBox CheckBox144;
    private CheckBox CheckBox145;
    private CheckBox CheckBox146;
    private CheckBox CheckBox147;
    private CheckBox CheckBox148;
    private CheckBox CheckBox149;
    private CheckBox CheckBox15;
    private CheckBox CheckBox150;
    private CheckBox CheckBox151;
    private CheckBox CheckBox152;
    private CheckBox CheckBox153;
    private CheckBox CheckBox154;
    private CheckBox CheckBox155;
    private CheckBox CheckBox156;
    private CheckBox CheckBox157;
    private CheckBox CheckBox158;
    private CheckBox CheckBox159;
    private CheckBox CheckBox16;
    private CheckBox CheckBox160;
    private CheckBox CheckBox161;
    private CheckBox CheckBox162;
    private CheckBox CheckBox163;
    private CheckBox CheckBox164;
    private CheckBox CheckBox165;
    private CheckBox CheckBox166;
    private CheckBox CheckBox167;
    private CheckBox CheckBox168;
    private CheckBox CheckBox169;
    private CheckBox CheckBox17;
    private CheckBox CheckBox170;
    private CheckBox CheckBox171;
    private CheckBox CheckBox172;
    private CheckBox CheckBox173;
    private CheckBox CheckBox174;
    private CheckBox CheckBox175;
    private CheckBox CheckBox176;
    private CheckBox CheckBox177;
    private CheckBox CheckBox178;
    private CheckBox CheckBox179;
    private CheckBox CheckBox18;
    private CheckBox CheckBox180;
    private CheckBox CheckBox181;
    private CheckBox CheckBox182;
    private CheckBox CheckBox183;
    private CheckBox CheckBox184;
    private CheckBox CheckBox185;
    private CheckBox CheckBox186;
    private CheckBox CheckBox187;
    private CheckBox CheckBox188;
    private CheckBox CheckBox189;
    private CheckBox CheckBox19;
    private CheckBox CheckBox190;
    private CheckBox CheckBox191;
    private CheckBox CheckBox192;
    private CheckBox CheckBox193;
    private CheckBox CheckBox194;
    private CheckBox CheckBox195;
    private CheckBox CheckBox196;
    private CheckBox CheckBox197;
    private CheckBox CheckBox198;
    private CheckBox CheckBox199;
    private CheckBox CheckBox2;
    private CheckBox CheckBox20;
    private CheckBox CheckBox200;
    private CheckBox CheckBox201;
    private CheckBox CheckBox202;
    private CheckBox CheckBox203;
    private CheckBox CheckBox204;
    private CheckBox CheckBox205;
    private CheckBox CheckBox206;
    private CheckBox CheckBox207;
    private CheckBox CheckBox208;
    private CheckBox CheckBox209;
    private CheckBox CheckBox21;
    private CheckBox CheckBox210;
    private CheckBox CheckBox211;
    private CheckBox CheckBox212;
    private CheckBox CheckBox213;
    private CheckBox CheckBox214;
    private CheckBox CheckBox215;
    private CheckBox CheckBox216;
    private CheckBox CheckBox217;
    private CheckBox CheckBox218;
    private CheckBox CheckBox219;
    private CheckBox CheckBox22;
    private CheckBox CheckBox220;
    private CheckBox CheckBox221;
    private CheckBox CheckBox222;
    private CheckBox CheckBox223;
    private CheckBox CheckBox224;
    private CheckBox CheckBox225;
    private CheckBox CheckBox226;
    private CheckBox CheckBox227;
    private CheckBox CheckBox228;
    private CheckBox CheckBox229;
    private CheckBox CheckBox23;
    private CheckBox CheckBox230;
    private CheckBox CheckBox231;
    private CheckBox CheckBox232;
    private CheckBox CheckBox233;
    private CheckBox CheckBox234;
    private CheckBox CheckBox235;
    private CheckBox CheckBox236;
    private CheckBox CheckBox237;
    private CheckBox CheckBox238;
    private CheckBox CheckBox239;
    private CheckBox CheckBox24;
    private CheckBox CheckBox240;
    private CheckBox CheckBox241;
    private CheckBox CheckBox242;
    private CheckBox CheckBox243;
    private CheckBox CheckBox244;
    private CheckBox CheckBox245;
    private CheckBox CheckBox246;
    private CheckBox CheckBox247;
    private CheckBox CheckBox248;
    private CheckBox CheckBox249;
    private CheckBox CheckBox25;
    private CheckBox CheckBox250;
    private CheckBox CheckBox251;
    private CheckBox CheckBox252;
    private CheckBox CheckBox253;
    private CheckBox CheckBox254;
    private CheckBox CheckBox255;
    private CheckBox CheckBox256;
    private CheckBox CheckBox257;
    private CheckBox CheckBox258;
    private CheckBox CheckBox259;
    private CheckBox CheckBox26;
    private CheckBox CheckBox260;
    private CheckBox CheckBox261;
    private CheckBox CheckBox262;
    private CheckBox CheckBox263;
    private CheckBox CheckBox264;
    private CheckBox CheckBox265;
    private CheckBox CheckBox266;
    private CheckBox CheckBox267;
    private CheckBox CheckBox268;
    private CheckBox CheckBox269;
    private CheckBox CheckBox27;
    private CheckBox CheckBox270;
    private CheckBox CheckBox271;
    private CheckBox CheckBox272;
    private CheckBox CheckBox273;
    private CheckBox CheckBox274;
    private CheckBox CheckBox275;
    private CheckBox CheckBox276;
    private CheckBox CheckBox277;
    private CheckBox CheckBox278;
    private CheckBox CheckBox279;
    private CheckBox CheckBox28;
    private CheckBox CheckBox280;
    private CheckBox CheckBox281;
    private CheckBox CheckBox282;
    private CheckBox CheckBox283;
    private CheckBox CheckBox284;
    private CheckBox CheckBox285;
    private CheckBox CheckBox286;
    private CheckBox CheckBox287;
    private CheckBox CheckBox288;
    private CheckBox CheckBox289;
    private CheckBox CheckBox29;
    private CheckBox CheckBox290;
    private CheckBox CheckBox291;
    private CheckBox CheckBox292;
    private CheckBox CheckBox293;
    private CheckBox CheckBox294;
    private CheckBox CheckBox295;
    private CheckBox CheckBox296;
    private CheckBox CheckBox297;
    private CheckBox CheckBox298;
    private CheckBox CheckBox299;
    private CheckBox CheckBox3;
    private CheckBox CheckBox30;
    private CheckBox CheckBox300;
    private CheckBox CheckBox301;
    private CheckBox CheckBox302;
    private CheckBox CheckBox303;
    private CheckBox CheckBox304;
    private CheckBox CheckBox305;
    private CheckBox CheckBox306;
    private CheckBox CheckBox307;
    private CheckBox CheckBox308;
    private CheckBox CheckBox309;
    private CheckBox CheckBox31;
    private CheckBox CheckBox310;
    private CheckBox CheckBox311;
    private CheckBox CheckBox312;
    private CheckBox CheckBox313;
    private CheckBox CheckBox314;
    private CheckBox CheckBox315;
    private CheckBox CheckBox316;
    private CheckBox CheckBox317;
    private CheckBox CheckBox318;
    private CheckBox CheckBox319;
    private CheckBox CheckBox32;
    private CheckBox CheckBox320;
    private CheckBox CheckBox321;
    private CheckBox CheckBox322;
    private CheckBox CheckBox323;
    private CheckBox CheckBox324;
    private CheckBox CheckBox325;
    private CheckBox CheckBox326;
    private CheckBox CheckBox327;
    private CheckBox CheckBox328;
    private CheckBox CheckBox329;
    private CheckBox CheckBox33;
    private CheckBox CheckBox330;
    private CheckBox CheckBox331;
    private CheckBox CheckBox332;
    private CheckBox CheckBox333;
    private CheckBox CheckBox334;
    private CheckBox CheckBox335;
    private CheckBox CheckBox336;
    private CheckBox CheckBox337;
    private CheckBox CheckBox338;
    private CheckBox CheckBox339;
    private CheckBox CheckBox34;
    private CheckBox CheckBox340;
    private CheckBox CheckBox341;
    private CheckBox CheckBox342;
    private CheckBox CheckBox343;
    private CheckBox CheckBox344;
    private CheckBox CheckBox345;
    private CheckBox CheckBox346;
    private CheckBox CheckBox347;
    private CheckBox CheckBox348;
    private CheckBox CheckBox349;
    private CheckBox CheckBox35;
    private CheckBox CheckBox350;
    private CheckBox CheckBox351;
    private CheckBox CheckBox352;
    private CheckBox CheckBox353;
    private CheckBox CheckBox354;
    private CheckBox CheckBox355;
    private CheckBox CheckBox356;
    private CheckBox CheckBox357;
    private CheckBox CheckBox358;
    private CheckBox CheckBox359;
    private CheckBox CheckBox36;
    private CheckBox CheckBox360;
    private CheckBox CheckBox361;
    private CheckBox CheckBox362;
    private CheckBox CheckBox363;
    private CheckBox CheckBox364;
    private CheckBox CheckBox365;
    private CheckBox CheckBox366;
    private CheckBox CheckBox367;
    private CheckBox CheckBox368;
    private CheckBox CheckBox369;
    private CheckBox CheckBox37;
    private CheckBox CheckBox370;
    private CheckBox CheckBox371;
    private CheckBox CheckBox372;
    private CheckBox CheckBox373;
    private CheckBox CheckBox374;
    private CheckBox CheckBox375;
    private CheckBox CheckBox376;
    private CheckBox CheckBox377;
    private CheckBox CheckBox378;
    private CheckBox CheckBox379;
    private CheckBox CheckBox38;
    private CheckBox CheckBox380;
    private CheckBox CheckBox381;
    private CheckBox CheckBox382;
    private CheckBox CheckBox383;
    private CheckBox CheckBox384;
    private CheckBox CheckBox385;
    private CheckBox CheckBox386;
    private CheckBox CheckBox387;
    private CheckBox CheckBox388;
    private CheckBox CheckBox389;
    private CheckBox CheckBox39;
    private CheckBox CheckBox390;
    private CheckBox CheckBox391;
    private CheckBox CheckBox392;
    private CheckBox CheckBox393;
    private CheckBox CheckBox394;
    private CheckBox CheckBox395;
    private CheckBox CheckBox396;
    private CheckBox CheckBox397;
    private CheckBox CheckBox398;
    private CheckBox CheckBox399;
    private CheckBox CheckBox4;
    private CheckBox CheckBox40;
    private CheckBox CheckBox400;
    private CheckBox CheckBox41;
    private CheckBox CheckBox42;
    private CheckBox CheckBox43;
    private CheckBox CheckBox44;
    private CheckBox CheckBox45;
    private CheckBox CheckBox46;
    private CheckBox CheckBox47;
    private CheckBox CheckBox48;
    private CheckBox CheckBox49;
    private CheckBox CheckBox5;
    private CheckBox CheckBox50;
    private CheckBox CheckBox51;
    private CheckBox CheckBox52;
    private CheckBox CheckBox53;
    private CheckBox CheckBox54;
    private CheckBox CheckBox55;
    private CheckBox CheckBox56;
    private CheckBox CheckBox57;
    private CheckBox CheckBox58;
    private CheckBox CheckBox59;
    private CheckBox CheckBox6;
    private CheckBox CheckBox60;
    private CheckBox CheckBox61;
    private CheckBox CheckBox62;
    private CheckBox CheckBox63;
    private CheckBox CheckBox64;
    private CheckBox CheckBox65;
    private CheckBox CheckBox66;
    private CheckBox CheckBox67;
    private CheckBox CheckBox68;
    private CheckBox CheckBox69;
    private CheckBox CheckBox7;
    private CheckBox CheckBox70;
    private CheckBox CheckBox71;
    private CheckBox CheckBox72;
    private CheckBox CheckBox73;
    private CheckBox CheckBox74;
    private CheckBox CheckBox75;
    private CheckBox CheckBox76;
    private CheckBox CheckBox77;
    private CheckBox CheckBox78;
    private CheckBox CheckBox79;
    private CheckBox CheckBox8;
    private CheckBox CheckBox80;
    private CheckBox CheckBox81;
    private CheckBox CheckBox82;
    private CheckBox CheckBox83;
    private CheckBox CheckBox84;
    private CheckBox CheckBox85;
    private CheckBox CheckBox86;
    private CheckBox CheckBox87;
    private CheckBox CheckBox88;
    private CheckBox CheckBox89;
    private CheckBox CheckBox9;
    private CheckBox CheckBox90;
    private CheckBox CheckBox91;
    private CheckBox CheckBox92;
    private CheckBox CheckBox93;
    private CheckBox CheckBox94;
    private CheckBox CheckBox95;
    private CheckBox CheckBox96;
    private CheckBox CheckBox97;
    private CheckBox CheckBox98;
    private CheckBox CheckBox99;
    private String[] dist;
    private Button submit;
    private TableRow[] tableRow;
    private TableRow tableRow1;
    private TableRow tableRow10;
    private TableRow tableRow11;
    private TableRow tableRow12;
    private TableRow tableRow13;
    private TableRow tableRow14;
    private TableRow tableRow15;
    private TableRow tableRow16;
    private TableRow tableRow17;
    private TableRow tableRow18;
    private TableRow tableRow19;
    private TableRow tableRow2;
    private TableRow tableRow20;
    private TableRow tableRow3;
    private TableRow tableRow4;
    private TableRow tableRow5;
    private TableRow tableRow6;
    private TableRow tableRow7;
    private TableRow tableRow8;
    private TableRow tableRow9;
    private CheckBox[] tv_s;
    private List<String> xuanzhong;
    
    public WellcodeShaixuanActivity() {
        this.CheckBox1 = null;
        this.CheckBox2 = null;
        this.CheckBox3 = null;
        this.CheckBox4 = null;
        this.CheckBox5 = null;
        this.CheckBox6 = null;
        this.CheckBox7 = null;
        this.CheckBox8 = null;
        this.CheckBox9 = null;
        this.CheckBox10 = null;
        this.CheckBox11 = null;
        this.CheckBox12 = null;
        this.CheckBox13 = null;
        this.CheckBox14 = null;
        this.CheckBox15 = null;
        this.CheckBox16 = null;
        this.CheckBox17 = null;
        this.CheckBox18 = null;
        this.CheckBox19 = null;
        this.CheckBox20 = null;
        this.CheckBox21 = null;
        this.CheckBox22 = null;
        this.CheckBox23 = null;
        this.CheckBox24 = null;
        this.CheckBox25 = null;
        this.CheckBox26 = null;
        this.CheckBox27 = null;
        this.CheckBox28 = null;
        this.CheckBox29 = null;
        this.CheckBox30 = null;
        this.CheckBox31 = null;
        this.CheckBox32 = null;
        this.CheckBox33 = null;
        this.CheckBox34 = null;
        this.CheckBox35 = null;
        this.CheckBox36 = null;
        this.CheckBox37 = null;
        this.CheckBox38 = null;
        this.CheckBox39 = null;
        this.CheckBox40 = null;
        this.CheckBox41 = null;
        this.CheckBox42 = null;
        this.CheckBox43 = null;
        this.CheckBox44 = null;
        this.CheckBox45 = null;
        this.CheckBox46 = null;
        this.CheckBox47 = null;
        this.CheckBox48 = null;
        this.CheckBox49 = null;
        this.CheckBox50 = null;
        this.CheckBox51 = null;
        this.CheckBox52 = null;
        this.CheckBox53 = null;
        this.CheckBox54 = null;
        this.CheckBox55 = null;
        this.CheckBox56 = null;
        this.CheckBox57 = null;
        this.CheckBox58 = null;
        this.CheckBox59 = null;
        this.CheckBox60 = null;
        this.CheckBox61 = null;
        this.CheckBox62 = null;
        this.CheckBox63 = null;
        this.CheckBox64 = null;
        this.CheckBox65 = null;
        this.CheckBox66 = null;
        this.CheckBox67 = null;
        this.CheckBox68 = null;
        this.CheckBox69 = null;
        this.CheckBox70 = null;
        this.CheckBox71 = null;
        this.CheckBox72 = null;
        this.CheckBox73 = null;
        this.CheckBox74 = null;
        this.CheckBox75 = null;
        this.CheckBox76 = null;
        this.CheckBox77 = null;
        this.CheckBox78 = null;
        this.CheckBox79 = null;
        this.CheckBox80 = null;
        this.CheckBox81 = null;
        this.CheckBox82 = null;
        this.CheckBox83 = null;
        this.CheckBox84 = null;
        this.CheckBox85 = null;
        this.CheckBox86 = null;
        this.CheckBox87 = null;
        this.CheckBox88 = null;
        this.CheckBox89 = null;
        this.CheckBox90 = null;
        this.CheckBox91 = null;
        this.CheckBox92 = null;
        this.CheckBox93 = null;
        this.CheckBox94 = null;
        this.CheckBox95 = null;
        this.CheckBox96 = null;
        this.CheckBox97 = null;
        this.CheckBox98 = null;
        this.CheckBox99 = null;
        this.CheckBox100 = null;
        this.CheckBox101 = null;
        this.CheckBox102 = null;
        this.CheckBox103 = null;
        this.CheckBox104 = null;
        this.CheckBox105 = null;
        this.CheckBox106 = null;
        this.CheckBox107 = null;
        this.CheckBox108 = null;
        this.CheckBox109 = null;
        this.CheckBox110 = null;
        this.CheckBox111 = null;
        this.CheckBox112 = null;
        this.CheckBox113 = null;
        this.CheckBox114 = null;
        this.CheckBox115 = null;
        this.CheckBox116 = null;
        this.CheckBox117 = null;
        this.CheckBox118 = null;
        this.CheckBox119 = null;
        this.CheckBox120 = null;
        this.CheckBox121 = null;
        this.CheckBox122 = null;
        this.CheckBox123 = null;
        this.CheckBox124 = null;
        this.CheckBox125 = null;
        this.CheckBox126 = null;
        this.CheckBox127 = null;
        this.CheckBox128 = null;
        this.CheckBox129 = null;
        this.CheckBox130 = null;
        this.CheckBox131 = null;
        this.CheckBox132 = null;
        this.CheckBox133 = null;
        this.CheckBox134 = null;
        this.CheckBox135 = null;
        this.CheckBox136 = null;
        this.CheckBox137 = null;
        this.CheckBox138 = null;
        this.CheckBox139 = null;
        this.CheckBox140 = null;
        this.CheckBox141 = null;
        this.CheckBox142 = null;
        this.CheckBox143 = null;
        this.CheckBox144 = null;
        this.CheckBox145 = null;
        this.CheckBox146 = null;
        this.CheckBox147 = null;
        this.CheckBox148 = null;
        this.CheckBox149 = null;
        this.CheckBox150 = null;
        this.CheckBox151 = null;
        this.CheckBox152 = null;
        this.CheckBox153 = null;
        this.CheckBox154 = null;
        this.CheckBox155 = null;
        this.CheckBox156 = null;
        this.CheckBox157 = null;
        this.CheckBox158 = null;
        this.CheckBox159 = null;
        this.CheckBox160 = null;
        this.CheckBox161 = null;
        this.CheckBox162 = null;
        this.CheckBox163 = null;
        this.CheckBox164 = null;
        this.CheckBox165 = null;
        this.CheckBox166 = null;
        this.CheckBox167 = null;
        this.CheckBox168 = null;
        this.CheckBox169 = null;
        this.CheckBox170 = null;
        this.CheckBox171 = null;
        this.CheckBox172 = null;
        this.CheckBox173 = null;
        this.CheckBox174 = null;
        this.CheckBox175 = null;
        this.CheckBox176 = null;
        this.CheckBox177 = null;
        this.CheckBox178 = null;
        this.CheckBox179 = null;
        this.CheckBox180 = null;
        this.CheckBox181 = null;
        this.CheckBox182 = null;
        this.CheckBox183 = null;
        this.CheckBox184 = null;
        this.CheckBox185 = null;
        this.CheckBox186 = null;
        this.CheckBox187 = null;
        this.CheckBox188 = null;
        this.CheckBox189 = null;
        this.CheckBox190 = null;
        this.CheckBox191 = null;
        this.CheckBox192 = null;
        this.CheckBox193 = null;
        this.CheckBox194 = null;
        this.CheckBox195 = null;
        this.CheckBox196 = null;
        this.CheckBox197 = null;
        this.CheckBox198 = null;
        this.CheckBox199 = null;
        this.CheckBox200 = null;
        this.CheckBox201 = null;
        this.CheckBox202 = null;
        this.CheckBox203 = null;
        this.CheckBox204 = null;
        this.CheckBox205 = null;
        this.CheckBox206 = null;
        this.CheckBox207 = null;
        this.CheckBox208 = null;
        this.CheckBox209 = null;
        this.CheckBox210 = null;
        this.CheckBox211 = null;
        this.CheckBox212 = null;
        this.CheckBox213 = null;
        this.CheckBox214 = null;
        this.CheckBox215 = null;
        this.CheckBox216 = null;
        this.CheckBox217 = null;
        this.CheckBox218 = null;
        this.CheckBox219 = null;
        this.CheckBox220 = null;
        this.CheckBox221 = null;
        this.CheckBox222 = null;
        this.CheckBox223 = null;
        this.CheckBox224 = null;
        this.CheckBox225 = null;
        this.CheckBox226 = null;
        this.CheckBox227 = null;
        this.CheckBox228 = null;
        this.CheckBox229 = null;
        this.CheckBox230 = null;
        this.CheckBox231 = null;
        this.CheckBox232 = null;
        this.CheckBox233 = null;
        this.CheckBox234 = null;
        this.CheckBox235 = null;
        this.CheckBox236 = null;
        this.CheckBox237 = null;
        this.CheckBox238 = null;
        this.CheckBox239 = null;
        this.CheckBox240 = null;
        this.CheckBox241 = null;
        this.CheckBox242 = null;
        this.CheckBox243 = null;
        this.CheckBox244 = null;
        this.CheckBox245 = null;
        this.CheckBox246 = null;
        this.CheckBox247 = null;
        this.CheckBox248 = null;
        this.CheckBox249 = null;
        this.CheckBox250 = null;
        this.CheckBox251 = null;
        this.CheckBox252 = null;
        this.CheckBox253 = null;
        this.CheckBox254 = null;
        this.CheckBox255 = null;
        this.CheckBox256 = null;
        this.CheckBox257 = null;
        this.CheckBox258 = null;
        this.CheckBox259 = null;
        this.CheckBox260 = null;
        this.CheckBox261 = null;
        this.CheckBox262 = null;
        this.CheckBox263 = null;
        this.CheckBox264 = null;
        this.CheckBox265 = null;
        this.CheckBox266 = null;
        this.CheckBox267 = null;
        this.CheckBox268 = null;
        this.CheckBox269 = null;
        this.CheckBox270 = null;
        this.CheckBox271 = null;
        this.CheckBox272 = null;
        this.CheckBox273 = null;
        this.CheckBox274 = null;
        this.CheckBox275 = null;
        this.CheckBox276 = null;
        this.CheckBox277 = null;
        this.CheckBox278 = null;
        this.CheckBox279 = null;
        this.CheckBox280 = null;
        this.CheckBox281 = null;
        this.CheckBox282 = null;
        this.CheckBox283 = null;
        this.CheckBox284 = null;
        this.CheckBox285 = null;
        this.CheckBox286 = null;
        this.CheckBox287 = null;
        this.CheckBox288 = null;
        this.CheckBox289 = null;
        this.CheckBox290 = null;
        this.CheckBox291 = null;
        this.CheckBox292 = null;
        this.CheckBox293 = null;
        this.CheckBox294 = null;
        this.CheckBox295 = null;
        this.CheckBox296 = null;
        this.CheckBox297 = null;
        this.CheckBox298 = null;
        this.CheckBox299 = null;
        this.CheckBox300 = null;
        this.CheckBox301 = null;
        this.CheckBox302 = null;
        this.CheckBox303 = null;
        this.CheckBox304 = null;
        this.CheckBox305 = null;
        this.CheckBox306 = null;
        this.CheckBox307 = null;
        this.CheckBox308 = null;
        this.CheckBox309 = null;
        this.CheckBox310 = null;
        this.CheckBox311 = null;
        this.CheckBox312 = null;
        this.CheckBox313 = null;
        this.CheckBox314 = null;
        this.CheckBox315 = null;
        this.CheckBox316 = null;
        this.CheckBox317 = null;
        this.CheckBox318 = null;
        this.CheckBox319 = null;
        this.CheckBox320 = null;
        this.CheckBox321 = null;
        this.CheckBox322 = null;
        this.CheckBox323 = null;
        this.CheckBox324 = null;
        this.CheckBox325 = null;
        this.CheckBox326 = null;
        this.CheckBox327 = null;
        this.CheckBox328 = null;
        this.CheckBox329 = null;
        this.CheckBox330 = null;
        this.CheckBox331 = null;
        this.CheckBox332 = null;
        this.CheckBox333 = null;
        this.CheckBox334 = null;
        this.CheckBox335 = null;
        this.CheckBox336 = null;
        this.CheckBox337 = null;
        this.CheckBox338 = null;
        this.CheckBox339 = null;
        this.CheckBox340 = null;
        this.CheckBox341 = null;
        this.CheckBox342 = null;
        this.CheckBox343 = null;
        this.CheckBox344 = null;
        this.CheckBox345 = null;
        this.CheckBox346 = null;
        this.CheckBox347 = null;
        this.CheckBox348 = null;
        this.CheckBox349 = null;
        this.CheckBox350 = null;
        this.CheckBox351 = null;
        this.CheckBox352 = null;
        this.CheckBox353 = null;
        this.CheckBox354 = null;
        this.CheckBox355 = null;
        this.CheckBox356 = null;
        this.CheckBox357 = null;
        this.CheckBox358 = null;
        this.CheckBox359 = null;
        this.CheckBox360 = null;
        this.CheckBox361 = null;
        this.CheckBox362 = null;
        this.CheckBox363 = null;
        this.CheckBox364 = null;
        this.CheckBox365 = null;
        this.CheckBox366 = null;
        this.CheckBox367 = null;
        this.CheckBox368 = null;
        this.CheckBox369 = null;
        this.CheckBox370 = null;
        this.CheckBox371 = null;
        this.CheckBox372 = null;
        this.CheckBox373 = null;
        this.CheckBox374 = null;
        this.CheckBox375 = null;
        this.CheckBox376 = null;
        this.CheckBox377 = null;
        this.CheckBox378 = null;
        this.CheckBox379 = null;
        this.CheckBox380 = null;
        this.CheckBox381 = null;
        this.CheckBox382 = null;
        this.CheckBox383 = null;
        this.CheckBox384 = null;
        this.CheckBox385 = null;
        this.CheckBox386 = null;
        this.CheckBox387 = null;
        this.CheckBox388 = null;
        this.CheckBox389 = null;
        this.CheckBox390 = null;
        this.CheckBox391 = null;
        this.CheckBox392 = null;
        this.CheckBox393 = null;
        this.CheckBox394 = null;
        this.CheckBox395 = null;
        this.CheckBox396 = null;
        this.CheckBox397 = null;
        this.CheckBox398 = null;
        this.CheckBox399 = null;
        this.CheckBox400 = null;
        this.tv_s = new CheckBox[400];
        this.tableRow1 = null;
        this.tableRow2 = null;
        this.tableRow3 = null;
        this.tableRow4 = null;
        this.tableRow5 = null;
        this.tableRow6 = null;
        this.tableRow7 = null;
        this.tableRow8 = null;
        this.tableRow9 = null;
        this.tableRow10 = null;
        this.tableRow11 = null;
        this.tableRow12 = null;
        this.tableRow13 = null;
        this.tableRow14 = null;
        this.tableRow15 = null;
        this.tableRow16 = null;
        this.tableRow17 = null;
        this.tableRow18 = null;
        this.tableRow19 = null;
        this.tableRow20 = null;
        this.tableRow = new TableRow[20];
        this.submit = null;
        this.xuanzhong = null;
        this.dist = null;
    }
    
    private void shu1(final int visibility) {
        for (int i = 0; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu10(final int visibility) {
        for (int i = 9; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu11(final int visibility) {
        for (int i = 10; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu12(final int visibility) {
        for (int i = 11; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu13(final int visibility) {
        for (int i = 12; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu14(final int visibility) {
        for (int i = 13; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu15(final int visibility) {
        for (int i = 14; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu16(final int visibility) {
        for (int i = 15; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu17(final int visibility) {
        for (int i = 16; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu18(final int visibility) {
        for (int i = 17; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu19(final int visibility) {
        for (int i = 18; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu2(final int visibility) {
        for (int i = 1; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu20(final int visibility) {
        for (int i = 19; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu3(final int visibility) {
        for (int i = 2; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu4(final int visibility) {
        for (int i = 3; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu5(final int visibility) {
        for (int i = 4; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu6(final int visibility) {
        for (int i = 5; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu7(final int visibility) {
        for (int i = 6; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu8(final int visibility) {
        for (int i = 7; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void shu9(final int visibility) {
        for (int i = 8; i < 400; i += 20) {
            this.tv_s[i].setVisibility(visibility);
        }
    }
    
    private void viCodeSizeShu(final int n) {
        switch (n) {
            default: {}
            case 1: {
                this.shu1(0);
                this.shu2(8);
                this.shu3(8);
                this.shu4(8);
                this.shu5(8);
                this.shu6(8);
                this.shu7(8);
                this.shu8(8);
                this.shu9(8);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 2: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(8);
                this.shu4(8);
                this.shu5(8);
                this.shu6(8);
                this.shu7(8);
                this.shu8(8);
                this.shu9(8);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 3: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(8);
                this.shu5(8);
                this.shu6(8);
                this.shu7(8);
                this.shu8(8);
                this.shu9(8);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 4: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(8);
                this.shu6(8);
                this.shu7(8);
                this.shu8(8);
                this.shu9(8);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 5: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(8);
                this.shu7(8);
                this.shu8(8);
                this.shu9(8);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 6: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(8);
                this.shu8(8);
                this.shu9(8);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 7: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(8);
                this.shu9(8);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 8: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(8);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 9: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(8);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 10: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(8);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 11: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(8);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 12: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(8);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 13: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(0);
                this.shu14(8);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 14: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(0);
                this.shu14(0);
                this.shu15(8);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 15: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(0);
                this.shu14(0);
                this.shu15(0);
                this.shu16(8);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 16: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(0);
                this.shu14(0);
                this.shu15(0);
                this.shu16(0);
                this.shu17(8);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 17: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(0);
                this.shu14(0);
                this.shu15(0);
                this.shu16(0);
                this.shu17(0);
                this.shu18(8);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 18: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(0);
                this.shu14(0);
                this.shu15(0);
                this.shu16(0);
                this.shu17(0);
                this.shu18(0);
                this.shu19(8);
                this.shu20(8);
                break;
            }
            case 19: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(0);
                this.shu14(0);
                this.shu15(0);
                this.shu16(0);
                this.shu17(0);
                this.shu18(0);
                this.shu19(0);
                this.shu20(8);
                break;
            }
            case 20: {
                this.shu1(0);
                this.shu2(0);
                this.shu3(0);
                this.shu4(0);
                this.shu5(0);
                this.shu6(0);
                this.shu7(0);
                this.shu8(0);
                this.shu9(0);
                this.shu10(0);
                this.shu11(0);
                this.shu12(0);
                this.shu13(0);
                this.shu14(0);
                this.shu15(0);
                this.shu16(0);
                this.shu17(0);
                this.shu18(0);
                this.shu19(0);
                this.shu20(0);
                break;
            }
        }
    }
    
    @Override
    protected void onCreate(final Bundle bundle) {
        super.onCreate(bundle);
        this.setContentView(R.layout.activity_wellcode_shaixuan);

        this.tv_s[0] = this.CheckBox1;
        this.tv_s[1] = this.CheckBox2;
        this.tv_s[2] = this.CheckBox3;
        this.tv_s[3] = this.CheckBox4;
        this.tv_s[4] = this.CheckBox5;
        this.tv_s[5] = this.CheckBox6;
        this.tv_s[6] = this.CheckBox7;
        this.tv_s[7] = this.CheckBox8;
        this.tv_s[8] = this.CheckBox9;
        this.tv_s[9] = this.CheckBox10;
        this.tv_s[10] = this.CheckBox11;
        this.tv_s[11] = this.CheckBox12;
        this.tv_s[12] = this.CheckBox13;
        this.tv_s[13] = this.CheckBox14;
        this.tv_s[14] = this.CheckBox15;
        this.tv_s[15] = this.CheckBox16;
        this.tv_s[16] = this.CheckBox17;
        this.tv_s[17] = this.CheckBox18;
        this.tv_s[18] = this.CheckBox19;
        this.tv_s[19] = this.CheckBox20;
        this.tv_s[20] = this.CheckBox21;
        this.tv_s[21] = this.CheckBox22;
        this.tv_s[22] = this.CheckBox23;
        this.tv_s[23] = this.CheckBox24;
        this.tv_s[24] = this.CheckBox25;
        this.tv_s[25] = this.CheckBox26;
        this.tv_s[26] = this.CheckBox27;
        this.tv_s[27] = this.CheckBox28;
        this.tv_s[28] = this.CheckBox29;
        this.tv_s[29] = this.CheckBox30;
        this.tv_s[30] = this.CheckBox31;
        this.tv_s[31] = this.CheckBox32;
        this.tv_s[32] = this.CheckBox33;
        this.tv_s[33] = this.CheckBox34;
        this.tv_s[34] = this.CheckBox35;
        this.tv_s[35] = this.CheckBox36;
        this.tv_s[36] = this.CheckBox37;
        this.tv_s[37] = this.CheckBox38;
        this.tv_s[38] = this.CheckBox39;
        this.tv_s[39] = this.CheckBox40;
        this.tv_s[40] = this.CheckBox41;
        this.tv_s[41] = this.CheckBox42;
        this.tv_s[42] = this.CheckBox43;
        this.tv_s[43] = this.CheckBox44;
        this.tv_s[44] = this.CheckBox45;
        this.tv_s[45] = this.CheckBox46;
        this.tv_s[46] = this.CheckBox47;
        this.tv_s[47] = this.CheckBox48;
        this.tv_s[48] = this.CheckBox49;
        this.tv_s[49] = this.CheckBox50;
        this.tv_s[50] = this.CheckBox51;
        this.tv_s[51] = this.CheckBox52;
        this.tv_s[52] = this.CheckBox53;
        this.tv_s[53] = this.CheckBox54;
        this.tv_s[54] = this.CheckBox55;
        this.tv_s[55] = this.CheckBox56;
        this.tv_s[56] = this.CheckBox57;
        this.tv_s[57] = this.CheckBox58;
        this.tv_s[58] = this.CheckBox59;
        this.tv_s[59] = this.CheckBox60;
        this.tv_s[60] = this.CheckBox61;
        this.tv_s[61] = this.CheckBox62;
        this.tv_s[62] = this.CheckBox63;
        this.tv_s[63] = this.CheckBox64;
        this.tv_s[64] = this.CheckBox65;
        this.tv_s[65] = this.CheckBox66;
        this.tv_s[66] = this.CheckBox67;
        this.tv_s[67] = this.CheckBox68;
        this.tv_s[68] = this.CheckBox69;
        this.tv_s[69] = this.CheckBox70;
        this.tv_s[70] = this.CheckBox71;
        this.tv_s[71] = this.CheckBox72;
        this.tv_s[72] = this.CheckBox73;
        this.tv_s[73] = this.CheckBox74;
        this.tv_s[74] = this.CheckBox75;
        this.tv_s[75] = this.CheckBox76;
        this.tv_s[76] = this.CheckBox77;
        this.tv_s[77] = this.CheckBox78;
        this.tv_s[78] = this.CheckBox79;
        this.tv_s[79] = this.CheckBox80;
        this.tv_s[80] = this.CheckBox81;
        this.tv_s[81] = this.CheckBox82;
        this.tv_s[82] = this.CheckBox83;
        this.tv_s[83] = this.CheckBox84;
        this.tv_s[84] = this.CheckBox85;
        this.tv_s[85] = this.CheckBox86;
        this.tv_s[86] = this.CheckBox87;
        this.tv_s[87] = this.CheckBox88;
        this.tv_s[88] = this.CheckBox89;
        this.tv_s[89] = this.CheckBox90;
        this.tv_s[90] = this.CheckBox91;
        this.tv_s[91] = this.CheckBox92;
        this.tv_s[92] = this.CheckBox93;
        this.tv_s[93] = this.CheckBox94;
        this.tv_s[94] = this.CheckBox95;
        this.tv_s[95] = this.CheckBox96;
        this.tv_s[96] = this.CheckBox97;
        this.tv_s[97] = this.CheckBox98;
        this.tv_s[98] = this.CheckBox99;
        this.tv_s[99] = this.CheckBox100;
        this.tv_s[100] = this.CheckBox101;
        this.tv_s[101] = this.CheckBox102;
        this.tv_s[102] = this.CheckBox103;
        this.tv_s[103] = this.CheckBox104;
        this.tv_s[104] = this.CheckBox105;
        this.tv_s[105] = this.CheckBox106;
        this.tv_s[106] = this.CheckBox107;
        this.tv_s[107] = this.CheckBox108;
        this.tv_s[108] = this.CheckBox109;
        this.tv_s[109] = this.CheckBox110;
        this.tv_s[110] = this.CheckBox111;
        this.tv_s[111] = this.CheckBox112;
        this.tv_s[112] = this.CheckBox113;
        this.tv_s[113] = this.CheckBox114;
        this.tv_s[114] = this.CheckBox115;
        this.tv_s[115] = this.CheckBox116;
        this.tv_s[116] = this.CheckBox117;
        this.tv_s[117] = this.CheckBox118;
        this.tv_s[118] = this.CheckBox119;
        this.tv_s[119] = this.CheckBox120;
        this.tv_s[120] = this.CheckBox121;
        this.tv_s[121] = this.CheckBox122;
        this.tv_s[122] = this.CheckBox123;
        this.tv_s[123] = this.CheckBox124;
        this.tv_s[124] = this.CheckBox125;
        this.tv_s[125] = this.CheckBox126;
        this.tv_s[126] = this.CheckBox127;
        this.tv_s[127] = this.CheckBox128;
        this.tv_s[128] = this.CheckBox129;
        this.tv_s[129] = this.CheckBox130;
        this.tv_s[130] = this.CheckBox131;
        this.tv_s[131] = this.CheckBox132;
        this.tv_s[132] = this.CheckBox133;
        this.tv_s[133] = this.CheckBox134;
        this.tv_s[134] = this.CheckBox135;
        this.tv_s[135] = this.CheckBox136;
        this.tv_s[136] = this.CheckBox137;
        this.tv_s[137] = this.CheckBox138;
        this.tv_s[138] = this.CheckBox139;
        this.tv_s[139] = this.CheckBox140;
        this.tv_s[140] = this.CheckBox141;
        this.tv_s[141] = this.CheckBox142;
        this.tv_s[142] = this.CheckBox143;
        this.tv_s[143] = this.CheckBox144;
        this.tv_s[144] = this.CheckBox145;
        this.tv_s[145] = this.CheckBox146;
        this.tv_s[146] = this.CheckBox147;
        this.tv_s[147] = this.CheckBox148;
        this.tv_s[148] = this.CheckBox149;
        this.tv_s[149] = this.CheckBox150;
        this.tv_s[150] = this.CheckBox151;
        this.tv_s[151] = this.CheckBox152;
        this.tv_s[152] = this.CheckBox153;
        this.tv_s[153] = this.CheckBox154;
        this.tv_s[154] = this.CheckBox155;
        this.tv_s[155] = this.CheckBox156;
        this.tv_s[156] = this.CheckBox157;
        this.tv_s[157] = this.CheckBox158;
        this.tv_s[158] = this.CheckBox159;
        this.tv_s[159] = this.CheckBox160;
        this.tv_s[160] = this.CheckBox161;
        this.tv_s[161] = this.CheckBox162;
        this.tv_s[162] = this.CheckBox163;
        this.tv_s[163] = this.CheckBox164;
        this.tv_s[164] = this.CheckBox165;
        this.tv_s[165] = this.CheckBox166;
        this.tv_s[166] = this.CheckBox167;
        this.tv_s[167] = this.CheckBox168;
        this.tv_s[168] = this.CheckBox169;
        this.tv_s[169] = this.CheckBox170;
        this.tv_s[170] = this.CheckBox171;
        this.tv_s[171] = this.CheckBox172;
        this.tv_s[172] = this.CheckBox173;
        this.tv_s[173] = this.CheckBox174;
        this.tv_s[174] = this.CheckBox175;
        this.tv_s[175] = this.CheckBox176;
        this.tv_s[176] = this.CheckBox177;
        this.tv_s[177] = this.CheckBox178;
        this.tv_s[178] = this.CheckBox179;
        this.tv_s[179] = this.CheckBox180;
        this.tv_s[180] = this.CheckBox181;
        this.tv_s[181] = this.CheckBox182;
        this.tv_s[182] = this.CheckBox183;
        this.tv_s[183] = this.CheckBox184;
        this.tv_s[184] = this.CheckBox185;
        this.tv_s[185] = this.CheckBox186;
        this.tv_s[186] = this.CheckBox187;
        this.tv_s[187] = this.CheckBox188;
        this.tv_s[188] = this.CheckBox189;
        this.tv_s[189] = this.CheckBox190;
        this.tv_s[190] = this.CheckBox191;
        this.tv_s[191] = this.CheckBox192;
        this.tv_s[192] = this.CheckBox193;
        this.tv_s[193] = this.CheckBox194;
        this.tv_s[194] = this.CheckBox195;
        this.tv_s[195] = this.CheckBox196;
        this.tv_s[196] = this.CheckBox197;
        this.tv_s[197] = this.CheckBox198;
        this.tv_s[198] = this.CheckBox199;
        this.tv_s[199] = this.CheckBox200;
        this.tv_s[200] = this.CheckBox201;
        this.tv_s[201] = this.CheckBox202;
        this.tv_s[202] = this.CheckBox203;
        this.tv_s[203] = this.CheckBox204;
        this.tv_s[204] = this.CheckBox205;
        this.tv_s[205] = this.CheckBox206;
        this.tv_s[206] = this.CheckBox207;
        this.tv_s[207] = this.CheckBox208;
        this.tv_s[208] = this.CheckBox209;
        this.tv_s[209] = this.CheckBox210;
        this.tv_s[210] = this.CheckBox211;
        this.tv_s[211] = this.CheckBox212;
        this.tv_s[212] = this.CheckBox213;
        this.tv_s[213] = this.CheckBox214;
        this.tv_s[214] = this.CheckBox215;
        this.tv_s[215] = this.CheckBox216;
        this.tv_s[216] = this.CheckBox217;
        this.tv_s[217] = this.CheckBox218;
        this.tv_s[218] = this.CheckBox219;
        this.tv_s[219] = this.CheckBox220;
        this.tv_s[220] = this.CheckBox221;
        this.tv_s[221] = this.CheckBox222;
        this.tv_s[222] = this.CheckBox223;
        this.tv_s[223] = this.CheckBox224;
        this.tv_s[224] = this.CheckBox225;
        this.tv_s[225] = this.CheckBox226;
        this.tv_s[226] = this.CheckBox227;
        this.tv_s[227] = this.CheckBox228;
        this.tv_s[228] = this.CheckBox229;
        this.tv_s[229] = this.CheckBox230;
        this.tv_s[230] = this.CheckBox231;
        this.tv_s[231] = this.CheckBox232;
        this.tv_s[232] = this.CheckBox233;
        this.tv_s[233] = this.CheckBox234;
        this.tv_s[234] = this.CheckBox235;
        this.tv_s[235] = this.CheckBox236;
        this.tv_s[236] = this.CheckBox237;
        this.tv_s[237] = this.CheckBox238;
        this.tv_s[238] = this.CheckBox239;
        this.tv_s[239] = this.CheckBox240;
        this.tv_s[240] = this.CheckBox241;
        this.tv_s[241] = this.CheckBox242;
        this.tv_s[242] = this.CheckBox243;
        this.tv_s[243] = this.CheckBox244;
        this.tv_s[244] = this.CheckBox245;
        this.tv_s[245] = this.CheckBox246;
        this.tv_s[246] = this.CheckBox247;
        this.tv_s[247] = this.CheckBox248;
        this.tv_s[248] = this.CheckBox249;
        this.tv_s[249] = this.CheckBox250;
        this.tv_s[250] = this.CheckBox251;
        this.tv_s[251] = this.CheckBox252;
        this.tv_s[252] = this.CheckBox253;
        this.tv_s[253] = this.CheckBox254;
        this.tv_s[254] = this.CheckBox255;
        this.tv_s[255] = this.CheckBox256;
        this.tv_s[256] = this.CheckBox257;
        this.tv_s[257] = this.CheckBox258;
        this.tv_s[258] = this.CheckBox259;
        this.tv_s[259] = this.CheckBox260;
        this.tv_s[260] = this.CheckBox261;
        this.tv_s[261] = this.CheckBox262;
        this.tv_s[262] = this.CheckBox263;
        this.tv_s[263] = this.CheckBox264;
        this.tv_s[264] = this.CheckBox265;
        this.tv_s[265] = this.CheckBox266;
        this.tv_s[266] = this.CheckBox267;
        this.tv_s[267] = this.CheckBox268;
        this.tv_s[268] = this.CheckBox269;
        this.tv_s[269] = this.CheckBox270;
        this.tv_s[270] = this.CheckBox271;
        this.tv_s[271] = this.CheckBox272;
        this.tv_s[272] = this.CheckBox273;
        this.tv_s[273] = this.CheckBox274;
        this.tv_s[274] = this.CheckBox275;
        this.tv_s[275] = this.CheckBox276;
        this.tv_s[276] = this.CheckBox277;
        this.tv_s[277] = this.CheckBox278;
        this.tv_s[278] = this.CheckBox279;
        this.tv_s[279] = this.CheckBox280;
        this.tv_s[280] = this.CheckBox281;
        this.tv_s[281] = this.CheckBox282;
        this.tv_s[282] = this.CheckBox283;
        this.tv_s[283] = this.CheckBox284;
        this.tv_s[284] = this.CheckBox285;
        this.tv_s[285] = this.CheckBox286;
        this.tv_s[286] = this.CheckBox287;
        this.tv_s[287] = this.CheckBox288;
        this.tv_s[288] = this.CheckBox289;
        this.tv_s[289] = this.CheckBox290;
        this.tv_s[290] = this.CheckBox291;
        this.tv_s[291] = this.CheckBox292;
        this.tv_s[292] = this.CheckBox293;
        this.tv_s[293] = this.CheckBox294;
        this.tv_s[294] = this.CheckBox295;
        this.tv_s[295] = this.CheckBox296;
        this.tv_s[296] = this.CheckBox297;
        this.tv_s[297] = this.CheckBox298;
        this.tv_s[298] = this.CheckBox299;
        this.tv_s[299] = this.CheckBox300;
        this.tv_s[300] = this.CheckBox301;
        this.tv_s[301] = this.CheckBox302;
        this.tv_s[302] = this.CheckBox303;
        this.tv_s[303] = this.CheckBox304;
        this.tv_s[304] = this.CheckBox305;
        this.tv_s[305] = this.CheckBox306;
        this.tv_s[306] = this.CheckBox307;
        this.tv_s[307] = this.CheckBox308;
        this.tv_s[308] = this.CheckBox309;
        this.tv_s[309] = this.CheckBox310;
        this.tv_s[310] = this.CheckBox311;
        this.tv_s[311] = this.CheckBox312;
        this.tv_s[312] = this.CheckBox313;
        this.tv_s[313] = this.CheckBox314;
        this.tv_s[314] = this.CheckBox315;
        this.tv_s[315] = this.CheckBox316;
        this.tv_s[316] = this.CheckBox317;
        this.tv_s[317] = this.CheckBox318;
        this.tv_s[318] = this.CheckBox319;
        this.tv_s[319] = this.CheckBox320;
        this.tv_s[320] = this.CheckBox321;
        this.tv_s[321] = this.CheckBox322;
        this.tv_s[322] = this.CheckBox323;
        this.tv_s[323] = this.CheckBox324;
        this.tv_s[324] = this.CheckBox325;
        this.tv_s[325] = this.CheckBox326;
        this.tv_s[326] = this.CheckBox327;
        this.tv_s[327] = this.CheckBox328;
        this.tv_s[328] = this.CheckBox329;
        this.tv_s[329] = this.CheckBox330;
        this.tv_s[330] = this.CheckBox331;
        this.tv_s[331] = this.CheckBox332;
        this.tv_s[332] = this.CheckBox333;
        this.tv_s[333] = this.CheckBox334;
        this.tv_s[334] = this.CheckBox335;
        this.tv_s[335] = this.CheckBox336;
        this.tv_s[336] = this.CheckBox337;
        this.tv_s[337] = this.CheckBox338;
        this.tv_s[338] = this.CheckBox339;
        this.tv_s[339] = this.CheckBox340;
        this.tv_s[340] = this.CheckBox341;
        this.tv_s[341] = this.CheckBox342;
        this.tv_s[342] = this.CheckBox343;
        this.tv_s[343] = this.CheckBox344;
        this.tv_s[344] = this.CheckBox345;
        this.tv_s[345] = this.CheckBox346;
        this.tv_s[346] = this.CheckBox347;
        this.tv_s[347] = this.CheckBox348;
        this.tv_s[348] = this.CheckBox349;
        this.tv_s[349] = this.CheckBox350;
        this.tv_s[350] = this.CheckBox351;
        this.tv_s[351] = this.CheckBox352;
        this.tv_s[352] = this.CheckBox353;
        this.tv_s[353] = this.CheckBox354;
        this.tv_s[354] = this.CheckBox355;
        this.tv_s[355] = this.CheckBox356;
        this.tv_s[356] = this.CheckBox357;
        this.tv_s[357] = this.CheckBox358;
        this.tv_s[358] = this.CheckBox359;
        this.tv_s[359] = this.CheckBox360;
        this.tv_s[360] = this.CheckBox361;
        this.tv_s[361] = this.CheckBox362;
        this.tv_s[362] = this.CheckBox363;
        this.tv_s[363] = this.CheckBox364;
        this.tv_s[364] = this.CheckBox365;
        this.tv_s[365] = this.CheckBox366;
        this.tv_s[366] = this.CheckBox367;
        this.tv_s[367] = this.CheckBox368;
        this.tv_s[368] = this.CheckBox369;
        this.tv_s[369] = this.CheckBox370;
        this.tv_s[370] = this.CheckBox371;
        this.tv_s[371] = this.CheckBox372;
        this.tv_s[372] = this.CheckBox373;
        this.tv_s[373] = this.CheckBox374;
        this.tv_s[374] = this.CheckBox375;
        this.tv_s[375] = this.CheckBox376;
        this.tv_s[376] = this.CheckBox377;
        this.tv_s[377] = this.CheckBox378;
        this.tv_s[378] = this.CheckBox379;
        this.tv_s[379] = this.CheckBox380;
        this.tv_s[380] = this.CheckBox381;
        this.tv_s[381] = this.CheckBox382;
        this.tv_s[382] = this.CheckBox383;
        this.tv_s[383] = this.CheckBox384;
        this.tv_s[384] = this.CheckBox385;
        this.tv_s[385] = this.CheckBox386;
        this.tv_s[386] = this.CheckBox387;
        this.tv_s[387] = this.CheckBox388;
        this.tv_s[388] = this.CheckBox389;
        this.tv_s[389] = this.CheckBox390;
        this.tv_s[390] = this.CheckBox391;
        this.tv_s[391] = this.CheckBox392;
        this.tv_s[392] = this.CheckBox393;
        this.tv_s[393] = this.CheckBox394;
        this.tv_s[394] = this.CheckBox395;
        this.tv_s[395] = this.CheckBox396;
        this.tv_s[396] = this.CheckBox397;
        this.tv_s[397] = this.CheckBox398;
        this.tv_s[398] = this.CheckBox399;
        this.tv_s[399] = this.CheckBox400;

        this.tableRow[0] = this.tableRow1;
        this.tableRow[1] = this.tableRow2;
        this.tableRow[2] = this.tableRow3;
        this.tableRow[3] = this.tableRow4;
        this.tableRow[4] = this.tableRow5;
        this.tableRow[5] = this.tableRow6;
        this.tableRow[6] = this.tableRow7;
        this.tableRow[7] = this.tableRow8;
        this.tableRow[8] = this.tableRow9;
        this.tableRow[9] = this.tableRow10;
        this.tableRow[10] = this.tableRow11;
        this.tableRow[11] = this.tableRow12;
        this.tableRow[12] = this.tableRow13;
        this.tableRow[13] = this.tableRow14;
        this.tableRow[14] = this.tableRow15;
        this.tableRow[15] = this.tableRow16;
        this.tableRow[16] = this.tableRow17;
        this.tableRow[17] = this.tableRow18;
        this.tableRow[18] = this.tableRow19;
        this.tableRow[19] = this.tableRow20;
        final Intent intent = this.getIntent();
        final int intValue = Integer.valueOf(intent.getStringExtra("hang"));
        final int intValue2 = Integer.valueOf(intent.getStringExtra("lie"));
        this.dist = intent.getStringArrayExtra("disabletubes");
        for (int i = 0; i < 20; ++i) {
            if (i >= intValue) {
            }
            else {
            }
        }
        this.viCodeSizeShu(intValue2);
        this.xuanzhong = new ArrayList<String>();
        for (int j = 0; j < this.tv_s.length; ++j) {
            this.tv_s[j].setChecked(true);
            if (this.dist != null) {
                for (int k = 0; k < this.dist.length; ++k) {
                    if (this.tv_s[j].getText().toString().equals(this.dist[k])) {
                        this.tv_s[j].setChecked(false);
                    }
                }
            }
        }
        this.submit.setOnClickListener(new View.OnClickListener() {
            public void onClick(final View view) {
                for (int i = 0; i < WellcodeShaixuanActivity.this.tv_s.length; ++i) {
                    if (!WellcodeShaixuanActivity.this.tv_s[i].isChecked()) {
                        WellcodeShaixuanActivity.this.xuanzhong.add(WellcodeShaixuanActivity.this.tv_s[i].getText().toString());
                    }
                }
                final Intent intent = new Intent();
                intent.putStringArrayListExtra("backlist", (ArrayList)WellcodeShaixuanActivity.this.xuanzhong);
                WellcodeShaixuanActivity.this.setResult(-1, intent);
                WellcodeShaixuanActivity.this.finish();
            }
        });
       
    }
}
